sudo: required
services:
  - docker


before_install:
  - docker build -t michaelios/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  michaelios/docker-react npm run test -- --coverage
